const Api = [
    {
    id:1,
    image: "images/LS1.jpg",
    category: "Landscape",
    name: "'Maverick'",
 },
 {
   id:2,
   image: "images/LS3.jpg",
   category: "Landscape",
   name: "'Tranquil Lakeside Retreat'",
},
 {
   id:3,
   image: "images/LS2.jpg",
   category: "Landscape",
   name: "'Golden Fields at Dusk'",
},
{
   id:4,
   image: "images/A6.jpg",
   category: "Abstract",
   name: "'Chromatic Serenity'",
},
{
   id:5,
   image: "images/A7.jpg",
   category: "Abstract",
   name: "'Aetherial Whispers'",
},
{
   id:6,
   image: "images/A8.jpg",
   category: "Abstract",
   name: "'Obsidian Shadows'",
},
{
   id:7,
   image: "images/Sketch4.jpg",
   category: "Sketches",
   name:"'Stone Henge'",
},
{
   id:8,
   image: "images/Sketch5.jpg",
   category: "Sketches",
   name:"'Babuji Maharaj'",
},
{
   id:9,
   image: "images/Sketch6.jpg",
   category: "Sketches",
   name:"'Babuji Maharaj'",
},
{
   id:10,
   image: "images/Sketch7.jpg",
   category: "Sketches",
   name:"'Babuji Maharaj'",
},
{
   id:11,
   image: "images/Sketch8.jpg",
   category: "Sketches",
   name:"'Chariji'",
},
{
   id:12,
   image: "images/Sketch9.jpg",
   category: "Sketches",
   name:"'Swami Vivekananda'",
},
{
   id:13,
   image: "images/Sketch10.jpg",
   category: "Sketches",
   name:"'Chariji'",
},
{
   id:14,
   image: "images/SG1.jpg",
   category: "Stained Glass",
   name:"'Prismatic Radiance'",
},
{
   id:15,
   image: "images/A12.jpg",
   category: "Abstract",
   name: "'Infinite Horizons'",
},
{
   id:16,
   image: "images/LS4.jpg",
   category: "Landscape",
   name: "'Majestic Mountain Peaks'",
},
{
   id:17,
   image: "images/LS5.jpg",
   category: "Landscape",
   name: "'Enchanted Forest Path'",
},
{
   id:18,
   image: "images/LS6.jpg",
   category: "Landscape",
   name: "'Coastal Serenity'",
},
{
   id:19,
   image: "images/LS7.jpg",
   category: "Landscape",
   name: "'Desert Oasis Mirage'",
},
{
   id:20,
   image: "images/LS8.jpg",
   category: "Landscape",
   name: "'Sunset Over the Horizon'",
},
{
   id:21,
   image: "images/LS9.jpg",
   category: "Landscape",
   name: "'Rolling Hills in Spring'",
},
{
   id:22,
   image: "images/LS10.jpg",
   category: "Landscape",
   name: "'Urban Jungle at Night'",
},
{
   id:23,
   image: "images/LS11.jpg",
   category: "Landscape",
   name: "'Windswept Coastal Cliffs'",
},
{
   id:24,
   image: "images/LS12.jpg",
   category: "Landscape",
   name: "'Whispers of the Wilderness'",
},
{
   id:25,
   image: "images/SG2.jpg",
   category: "Stained Glass",
   name:"'Babuji Maharaj'",
},
{
   id:26,
   image: "images/A2.jpg",
   category: "Buy",
   price: "Rs.20000",
   name: "'Lalaji Maharaj'",
},
{
   id:27,
   image: "images/A3.jpg",
   category: "Abstract",
   name: "'Infinite Possibilities'",
},

{
   id:28,
   image: "images/A4.jpg",
   category: "Abstract",
   name: "'Temporal Dreamscape'",
},
{
   id:29,
   image: "images/A5.jpg",
   category: "Abstract",
   name: "'Evolving Echoes'",
},
{
   id:30,
   image: "images/Sketch1.jpg",
   category: "Sketches",
   name:"'Chariji'",
},
{
   id:31,
   image: "images/Sketch2.jpg",
   category: "Sketches",
   name:"'Mount Rushmore'",
},
{
   id:32,
   image: "images/Sketch3.jpg",
   category: "Sketches",
   name:"'Meher Baba'",
},
{
   id:33,
   image: "images/Sketch11.jpg",
   category: "Sketches",
   name:"'Babuji'",
},
{
   id:34,
   image: "images/LS13.jpg",
   category: "Landscape",
   name: "'Tranquil Valley'",
},
{
   id:35,
   image: "images/LS14.jpg",
   category: "Landscape",
   name: "'Misty Mountain Dawn'",
},
{
   id:36,
   image: "images/LS15.jpg",
   category: "Landscape",
   name: "'Rustic Riverscape'",
},
{
   id:37,
   image: "images/LS16.jpg",
   category: "Landscape",
   name: "'Serenity in the Highlands'",
},
{
   id:38,
   image: "images/LS17.jpg",
   category: "Landscape",
   name: "'Golden Fields of Harves'",
},
{
   id:39,
   image: "images/LS18.jpg",
   category: "Landscape",
   name: "'Enchanted Forest Retreat'",
},
{
   id:40,
   image: "images/LS19.jpg",
   category: "Landscape",
   name: "'Sunset Over the Lake'",
},
{
   id:41,
   image: "images/LS20.jpg",
   category: "Landscape",
   name: "'Crimson Canyon Views'",
},
{
   id:42,
   image: "images/LS21.jpg",
   category: "Landscape",
   name: "'Eternal Desert Dunes'",
},
{
   id:43,
   image: "images/LS22.jpg",
   category: "Landscape",
   name: "'Coastal Breezes'",
},
{
   id:44,
   image: "images/LS23.jpg",
   category: "Landscape",
   name: "'Moonlit Meadow Reflections'",
},
{
   id:45,
   image: "images/A9.jpg",
   category: "Abstract",
   name: "'Vivid Dreamscape'",
},
{
   id:46,
   image: "images/A10.jpg",
   category: "Abstract",
   name: "'Ethereal Illusions'",
},
{
   id:47,
   image: "images/A11.jpg",
   category: "Abstract",
   name: "'Ethereal Illusions'",
},
{
   id:48,
   image: "images/A1.jpg",
   category: "Abstract",
   name: "'Ethereal Expressions'",
},
{
   id:49,
   image: "images/A13.jpg",
   category: "Abstract",
   name: "'Harmony in Chaos'",
},
{
   id:50,
   image: "images/A14.jpg",
   category: "Abstract",
   name: "'Whispers of Color'",
},
{
   id:51,
   image: "images/A15.jpg",
   category: "Abstract",
   name: "'Rhythmic Abstractions'",
},
{
   id:52,
   image: "images/A16.jpg",
   category: "Abstract",
   name: "'Luminous Geometry'",
},
{
   id:53,
   image: "images/A17.jpg",
   category: "Abstract",
   name: "'Surreal Symphony'",
},
{
   id:54,
   image: "images/A18.jpg",
   category: "Abstract",
   name: "'Mystic Mindscapes'",
},
{
   id:55,
   image: "images/A19.jpg",
   category: "Abstract",
   name: "'Chroma Fusion'",
},
{
   id:56,
   image: "images/A20.jpg",
   category: "Abstract",
   name: "'Turbulent Tranquility'",
},
{
   id:57,
   image: "images/A21.jpg",
   category: "Abstract",
   name: "'Astral Echoes'",
},
{
   id:58,
   image: "images/A22.jpg",
   category: "Abstract",
   name: "'Abstract Enigma'",
},
{
   id:59,
   image: "images/A23.jpg",
   category: "Abstract",
   name: "'Radiant Aberrations'",
},
{
   id:60,
   image: "images/A24.jpg",
   category: "Abstract",
   name: "'Temporal Fluctuations'",
},
{
   id:61,
   image: "images/A25.jpg",
   category: "Abstract",
   name: "'Chaos and Harmony'",
},
{
   id:62,
   image: "images/A26.jpg",
   category: "Abstract",
   name: "'Colorful Whirlwind'",
},
{
   id:63,
   image: "images/A27.jpg",
   category: "Abstract",
   name: "'Transcendent Realms'",
},
{
   id:64,
   image: "images/A28.jpg",
   category: "Abstract",
   name: "'Ephemeral Echoes'",
},
{
   id:65,
   image: "images/A29.jpg",
   category: "Abstract",
   name: "'Metaphysical Mirage'",
},
{
   id:66,
   image: "images/A30.jpg",
   category: "Abstract",
   name: "'Spectrum Alchemy'",
},
{
   id:67,
   image: "images/A31.jpg",
   category: "Abstract",
   name: "'Interstellar Odyssey'",
},
{
   id:68,
   image: "images/A32.jpg",
   category: "Abstract",
   name: "'Aurora Splendor'",
},
{
   id:69,
   image: "images/A33.jpg",
   category: "Abstract",
   name: "'Symphonic Abstractions'",
},
{
   id:70,
   image: "images/A34.jpg",
   category: "Abstract",
   name: "'Cascading Hues'",
},
{
   id:71,
   image: "images/A35.jpg",
   category: "Abstract",
   name: "'Transcendental Pulse'",
},
{
   id:72,
   image: "images/A36.jpg",
   category: "Abstract",
   name: "'Labyrinth of Colors'",
},
{
   id:73,
   image: "images/A37.jpg",
   category: "Abstract",
   name: "'Radiant Aberrations'",
},
{
   id:74,
   image: "images/A38.jpg",
   category: "Abstract",
   name: "'Mystical Paradox'",
},
{
   id:75,
   image: "images/A39.jpg",
   category: "Abstract",
   name: "'Abstract Reverie'",
},
{
   id:76,
   image: "images/A40.jpg",
   category: "Abstract",
   name: "'Vibrant Dimensions'",
},
{
   id:77,
   image: "images/A41.jpg",
   category: "Abstract",
   name: "'Radiant Aberrations'",
},
{
   id:78,
   image: "images/A42.jpg",
   category: "Abstract",
   name: "'Ethereal Euphoria'",
},
{
   id:79,
   image: "images/A43.jpg",
   category: "Abstract",
   name: "'Kaleidoscopic Whispers'",
},
{
   id:80,
   image: "images/A44.jpg",
   category: "Abstract",
   name: "'Chromatic Odyssey'",
},
{
   id:81,
   image: "images/LS24.jpg",
   category: "Landscape",
   name: "'Moonlit Meadow Reflections'",
},
{
   id:82,
   image: "images/LS25.jpg",
   category: "Landscape",
   name: "'Emerald Lakeside Serenity'",
},
{
   id:83,
   image: "images/LS26.jpg",
   category: "Landscape",
   name: "'Majestic Mountain Majesty'",
},
{
   id:84,
   image: "images/LS27.jpg",
   category: "Landscape",
   name: "'Whispering Willow Woods'",
},
{
   id:85,
   image: "images/LS28.jpg",
   category: "Landscape",
   name: "'Azure Skies Overlook'",
},
{
   id:86,
   image: "images/LS29.jpg",
   category: "Landscape",
   name: "'Autumn's Painted Palette'",
},
{
   id:87,
   image: "images/LS30.jpg",
   category: "Landscape",
   name: "'Mystic Marshlands'",
},
{
   id:88,
   image: "images/LS31.jpg",
   category: "Landscape",
   name: "'Alpine Tranquility'",
},
{
   id:89,
   image: "images/LS32.jpg",
   category: "Landscape",
   name: "'Hidden Waterfall Oasis'",
},
{
   id:90,
   image: "images/LS33.jpg",
   category: "Landscape",
   name: "'Aurora Over the Fjords'",
},
{
   id:91,
   image: "images/LS34.jpg",
   category: "Landscape",
   name: "'Moonlit Meadow Reflections'",
},
{
   id:92,
   image: "images/LS35.jpg",
   category: "Landscape",
   name: "Tranquil Tundra Vistas'",
},

{
   id:94,
   image: "images/A48.jpg",
   category: "Abstract",
   name: "'Ephemeral Echoes'",
},
{
   id:95,
   image: "images/A49.jpg",
   category: "Abstract",
   name: "'Celestial Harmony'",
},
{
   id:96,
   image: "images/A50.jpg",
   category: "Abstract",
   name: "'Vibrant Dreamscape'",
},
{
   id:97,
   image: "images/A51.jpg",
   category: "Abstract",
   name: "'Temporal Fusion'",
},
{
   id:98,
   image: "images/A52.jpg",
   category: "Abstract",
   name: "'Whispering Cosmic Chaos'",
},
{
   id:99,
   image: "images/A53.jpg",
   category: "Abstract",
   name: "'Infinite Possibilities'",
},
{
   id:100,
   image: "images/A54.jpg",
   category: "Abstract",
   name: "'Aurora Borealis Reverie'",
},
{
   id:101,
   image: "images/A55.jpg",
   category: "Abstract",
   name: "'Metamorphic Symphony'",
},
{
   id:102,
   image: "images/A56.jpg",
   category: "Abstract",
   name: "'Abstract Alchemy'",
},
{
   id:103,
   image: "images/A57.jpg",
   category: "Abstract",
   name: "'Spectral Cascade'",
},

{
   id:104,
   image: "images/A59.jpg",
   category: "Abstract",
   name: "'Mystical Convergence'",
},
{
   id:105,
   image: "images/A60.jpg",
   category: "Abstract",
   name: "'Resonant Reflections'",
},
{
   id:106,
   image: "images/A61.jpg",
   category: "Abstract",
   name: "'Kaleidoscopic Rhapsody",
},
{
   id:107,
   image: "images/A62.jpg",
   category: "Abstract",
   name: "'Ethereal Transcendence'",
},
{
   id:108,
   image: "images/A63.jpg",
   category: "Abstract",
   name: "'Geometric Abstractions'",
},
{
   id:109,
   image: "images/A64.jpg",
   category: "Abstract",
   name: "'Impressionistic Whirlwind'",
},
{
   id:110,
   image: "images/A65.jpg",
   category: "Abstract",
   name: "'Interstellar Reverberations'",
},
{
   id:111,
   image: "images/A66.jpg",
   category: "Abstract",
   name: "'Synaptic Splendor'",
},
{
   id:112,
   image: "images/A67.jpg",
   category: "Abstract",
   name: "'Surreal Spectrum'",
},
{
   id:113,
   image: "images/A68.jpg",
   category: "Abstract",
   name: "'Harmonic Illusions'",
},
{
   id:114,
   image: "images/A69.jpg",
   category: "Abstract",
   name: "'Evolving Dimensions'",
},
{
   id:115,
   image: "images/LS36.jpg",
   category: "Landscape",
   name: "'Misty Horizon Tranquility'",
},
{
   id:116,
   image: "images/LS37.jpg",
   category: "Landscape",
   name: "'Ethereal Valley Dreams'",
},
{
   id:117,
   image: "images/LS38.jpg",
   category: "Landscape",
   name: "'Sunset Serenity Overlook'",
},
{
   id:118,
   image: "images/LS39.jpg",
   category: "Landscape",
   name: "'Golden Fields of Solitude'",
},
{
   id:119,
   image: "images/LS40.jpg",
   category: "Landscape",
   name: "'Riverside Whispers at Dusk'",
},
{
   id:120,
   image: "images/A70.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:121,
   image: "images/A71.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:122,
   image: "images/A72.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:123,
   image: "images/A73.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:124,
   image: "images/A74.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:125,
   image: "images/A75.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:126,
   image: "images/A76.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:127,
   image: "images/A77.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:128,
   image: "images/A78.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:129,
   image: "images/A79.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:130,
   image: "images/A80.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:131,
   image: "images/A81.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:132,
   image: "images/A82.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:133,
   image: "images/A83.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:134,
   image: "images/A84.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:135,
   image: "images/A85.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:136,
   image: "images/A86.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:137,
   image: "images/A87.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:138,
   image: "images/A88.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:139,
   image: "images/A89.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:140,
   image: "images/A90.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:141,
   image: "images/A91.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:142,
   image: "images/A92.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:143,
   image: "images/A93.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:144,
   image: "images/A94.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:145,
   image: "images/A95.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:146,
   image: "images/A96.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:147,
   image: "images/A97.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:148,
   image: "images/A98.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:149,
   image: "images/A99.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:150,
   image: "images/A100.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:151,
   image: "images/A101.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:152,
   image: "images/A102.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:153,
   image: "images/A103.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:154,
   image: "images/A104.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:155,
   image: "images/A105.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:156,
   image: "images/A106.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:157,
   image: "images/A107.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:158,
   image: "images/A108.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:159,
   image: "images/A109.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:160,
   image: "images/A110.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:161,
   image: "images/A111.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:162,
   image: "images/A112.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:163,
   image: "images/A113.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:164,
   image: "images/A114.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:165,
   image: "images/A115.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:166,
   image: "images/A116.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:167,
   image: "images/A117.jpg",
   category: "Abstract",
   name: "'Heart & Veins'",
},
{
   id:168,
   image: "images/SG3.jpg",
   category: "Stained Glass",
   name:"'Reflective Index'",
},
{
   id:169,
   image: "images/SG4.jpg",
   category: "Stained Glass",
   name:"'Symmetric-Flowers'",
},
{
   id:170,
   image: "images/SG5.jpg",
   category: "Stained Glass",
   name:"'Mirroring'",
},
{
   id:171,
   image: "images/SG6.jpg",
   category: "Stained Glass",
   name:"'Glass Beings'",
},
{
   id:172,
   image: "images/SG7.jpg",
   category: "Stained Glass",
   name:"'Abstract Glass'",
},
{
   id:173,
   image: "images/SG8.jpg",
   category: "Stained Glass",
   name:"'Blue Lotus'",
},


];

export default Api;